import re
from typing import List, Dict, Any


def sanitize_search_query(raw_query: str) -> str: # ArXiv's search can be very sensitive to special characters, so we want to sanitize the LLM-generated query to improve the chances of getting relevant results. This function extracts the most relevant terms from the raw query, removing special characters and limiting the length to a reasonable number of terms.

    cleaned = raw_query.strip()

    quoted_match = re.search(r'"([^"]+)"', cleaned) # If the LLM provided a quoted search phrase, we prioritize that as it indicates a more specific intent. We extract the content within the quotes for our search query, as this is likely to yield more relevant results on ArXiv.
    
    if quoted_match:
        cleaned = quoted_match.group(1) # If there are no quotes, we take the last line of the response, which often contains the most relevant keywords or summary generated by the LLM. This is a heuristic to extract meaningful search terms from potentially verbose responses.

    cleaned = cleaned.splitlines()[-1].strip().strip('"\'')
    cleaned = re.sub(r"\s+", " ", cleaned)

    stop_words = {
        "a", "an", "and", "are", "as", "at", "be", "by", "can", "for",
        "from", "get", "how", "i", "in", "is", "it", "of", "on", "or",
        "our", "should", "that", "the", "this", "to", "using", "we",
        "what", "when", "where", "which", "who", "with"
    }

    terms = [
        term
        for term in re.findall(r"[A-Za-z0-9][A-Za-z0-9+\-.]*", cleaned)
        if term.lower() not in stop_words
    ]
    return " ".join(terms[:8])


def build_research_queries(question: str, llm_query: str) -> List[str]:
    queries = []

    # 1. Prioritize what the LLM generated (it's supposed to be the optimized phrase!)
    # We just strip accidental quotes or whitespace it might have generated.
    llm_clean = llm_query.strip().strip('"\'')
    if llm_clean:
        queries.append(llm_clean)

    # 2. Fallback to the user's raw question terms if the LLM output was empty
    question_query = sanitize_search_query(question)
    if question_query and question_query not in queries:
        queries.append(question_query)

    return queries


def get_last_user_message(history: List[Dict[str, Any]]) -> str:
    for message in reversed(history):
        if message.get("role") == "user" and message.get("content"):
            return str(message["content"]).strip()
    return ""


def is_follow_up_query(query: str) -> bool:
    normalized = re.sub(r"\s+", " ", query.strip().lower())
    if len(normalized.split()) <= 6:
        return True

    follow_up_markers = {
        "detail", "details", "more", "more detail", "more details",
        "explain", "elaborate", "expand", "clarify", "that", "this", "it"
    }

    return any(marker in normalized for marker in follow_up_markers)


def build_contextual_query(query: str, history: List[Dict[str, Any]]) -> str:
    last_user_message = get_last_user_message(history)

    if not last_user_message:
        return query

    if is_follow_up_query(query):
        return f"{last_user_message}. Follow-up question: {query}"

    return query


# Helper: format conversation
def format_history(history):

    if not history:
        return "No previous conversation."

    formatted = []

    for msg in history:
        role = "User" if msg["role"] == "user" else "AI Assistant"
        formatted.append(f"{role}: {msg['content']}")

    return "\n".join(formatted)

