import os
import re
import json
import requests
from dotenv import load_dotenv
from typing import TypedDict, List, Dict, Any
from pydantic.v1 import SecretStr

from supabase import create_client
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq

load_dotenv()


def require_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value

# -------------------------------
# LLM (Groq)
# -------------------------------

llm = ChatGroq(
    temperature=0,
    model="llama-3.1-8b-instant",
    api_key=SecretStr(require_env("GROQ_API_KEY")),
    stop_sequences=[]
)

# -------------------------------
# Supabase Client
# -------------------------------

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

supabase = create_client(require_env("SUPABASE_URL"), require_env("SUPABASE_KEY"))

# -------------------------------
# Jina Embedding API
# -------------------------------

JINA_API_KEY = os.getenv("JINA_API_KEY")
JINA_EMBEDDING_MODEL = os.getenv("JINA_EMBEDDING_MODEL", "jina-embeddings-v3")
JINA_QUERY_TASK = os.getenv("JINA_QUERY_TASK", "retrieval.query")
JINA_EMBEDDING_DIMENSIONS = int(os.getenv("JINA_EMBEDDING_DIMENSIONS", "1024"))

session = requests.Session()


def get_embedding(text: str):

    response = session.post(
        "https://api.jina.ai/v1/embeddings",
        headers={
            "Authorization": f"Bearer {JINA_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": JINA_EMBEDDING_MODEL,
            "task": JINA_QUERY_TASK,
            "input": text
        },
        timeout=30
    )

    if response.status_code != 200:
        raise RuntimeError(
            f"Jina embedding API error: {response.status_code} - {response.text}"
        )

    embedding = response.json()["data"][0]["embedding"]

    if len(embedding) != JINA_EMBEDDING_DIMENSIONS:
        raise RuntimeError(
            f"Jina embedding dimension mismatch: expected {JINA_EMBEDDING_DIMENSIONS}, got {len(embedding)}"
        )

    return embedding


def sanitize_arxiv_query(raw_query: str) -> str: # ArXiv's search can be very sensitive to special characters, so we want to sanitize the LLM-generated query to improve the chances of getting relevant results. This function extracts the most relevant terms from the raw query, removing special characters and limiting the length to a reasonable number of terms.

    cleaned = raw_query.strip()

    quoted_match = re.search(r'"([^"]+)"', cleaned) # If the LLM provided a quoted search phrase, we prioritize that as it indicates a more specific intent. We extract the content within the quotes for our search query, as this is likely to yield more relevant results on ArXiv.
    
    if quoted_match:
        cleaned = quoted_match.group(1) # If there are no quotes, we take the last line of the response, which often contains the most relevant keywords or summary generated by the LLM. This is a heuristic to extract meaningful search terms from potentially verbose responses.

    cleaned = cleaned.splitlines()[-1].strip().strip('"\'')
    cleaned = re.sub(r"\s+", " ", cleaned)

    stop_words = {
        "a", "an", "and", "are", "as", "at", "be", "by", "can", "for",
        "from", "get", "how", "i", "in", "is", "it", "of", "on", "or",
        "our", "should", "that", "the", "this", "to", "using", "we",
        "what", "when", "where", "which", "who", "with"
    }

    terms = [
        term
        for term in re.findall(r"[A-Za-z0-9][A-Za-z0-9+\-.]*", cleaned)
        if term.lower() not in stop_words
    ]
    return " ".join(terms[:8])


def build_arxiv_queries(question: str, llm_query: str) -> List[str]:
    queries = []

    question_query = sanitize_arxiv_query(question)
    if question_query:
        queries.append(question_query)

    llm_sanitized = sanitize_arxiv_query(llm_query)
    if llm_sanitized and llm_sanitized not in queries:
        queries.append(llm_sanitized)

    return queries


def get_last_user_message(history: List[Dict[str, Any]]) -> str:
    for message in reversed(history):
        if message.get("role") == "user" and message.get("content"):
            return str(message["content"]).strip()
    return ""


def is_follow_up_query(query: str) -> bool:
    normalized = re.sub(r"\s+", " ", query.strip().lower())
    if len(normalized.split()) <= 6:
        return True

    follow_up_markers = {
        "detail", "details", "more", "more detail", "more details",
        "explain", "elaborate", "expand", "clarify", "that", "this", "it"
    }

    return any(marker in normalized for marker in follow_up_markers)


def build_contextual_query(query: str, history: List[Dict[str, Any]]) -> str:
    last_user_message = get_last_user_message(history)

    if not last_user_message:
        return query

    if is_follow_up_query(query):
        return f"{last_user_message}. Follow-up question: {query}"

    return query


# -------------------------------
# Agent State
# -------------------------------

class AgentState(TypedDict): # This is the state that will be passed through each node of the agent's workflow. this is for langgraph's StateGraph and allows us to have a clear and consistent structure for the data that the agent operates on. By defining this as a TypedDict, we get type checking and autocompletion benefits when working with the agent's state in our code.
    query: str
    chat_history: List[Dict[str, Any]]
    context: str
    sources: List[str]
    needs_research: bool
    response: str


# -------------------------------
# Helper: format conversation
# -------------------------------

def format_history(history):

    if not history:
        return "No previous conversation."

    formatted = []

    for msg in history:
        role = "User" if msg["role"] == "user" else "AI Assistant"
        formatted.append(f"{role}: {msg['content']}")

    return "\n".join(formatted)


# -------------------------------
# Supabase Retrieval
# -------------------------------

def retrieve_documents(query: str):

    query_embedding = get_embedding(query)

    response = supabase.rpc(
        "match_documents",
        {
            "query_embedding": query_embedding,
            "match_count": 5
        }
    ).execute()

    response_rows = response.data if isinstance(response.data, list) else []

    if not response_rows:
        return [], []

    documents = [str(row["content"]) for row in response_rows if isinstance(row, dict) and "content" in row]

    metadatas = []
    for row in response_rows:
        if not isinstance(row, dict):
            continue
        m = row.get("metadata", {})
        if isinstance(m, str):
            try:
                m = json.loads(m)
            except Exception:
                m = {}
        metadatas.append(m if isinstance(m, dict) else {})

    sources_with_scores = [
        f"{metadata.get('source', 'Unknown')} ({row.get('similarity', 0):.4f})"
        for metadata, row in zip(metadatas, response_rows)
        if isinstance(row, dict)
    ]

    print(
        f"[RETRIEVAL] {len(documents)} docs, sources: {sources_with_scores}"
    )

    return documents, metadatas


# -------------------------------
# Node 1: Retrieve Knowledge
# -------------------------------

def retrieve_and_check(state: AgentState):

    print("--- NODE: RETRIEVE & CHECK ---")

    query = state["query"]
    history_str = format_history(state["chat_history"])
    contextual_query = build_contextual_query(query, state["chat_history"])

    if contextual_query != query:
        print(f"[QUERY REWRITE] Retrieval query expanded to: {contextual_query}")

    documents, metadatas = retrieve_documents(contextual_query)

    context_text = "\n\n".join(str(document) for document in documents)

    sources = list(
        {
            metadata.get("source", "Unknown")
            for metadata in metadatas
            if metadata
        }
    )
    sources = [s for s in sources if s != "Unknown"]

    decision_prompt = f"""
You are a strict evaluator.

Does the retrieved context contain enough relevant information to answer the query?

Reply ONLY "YES" or "NO".

Conversation History:
{history_str}

Query:
{contextual_query}

Context:
{context_text}
"""

    decision_message = llm.invoke(decision_prompt)
    decision = str(getattr(decision_message, "content", "")).strip().upper()

    print("Knowledge Check:", decision)

    needs_research = "NO" in decision or not context_text.strip() # If the LLM is unsure or explicitly says "NO", or if there is no retrieved context, we will proceed to the research step to try to find more information before attempting to generate an answer.

    return {
        "query": state["query"],
        "chat_history": state["chat_history"],
        "context": context_text,
        "sources": sources,
        "needs_research": needs_research, # how to route the workflow based on whether we need to do research or can generate an answer directly from retrieved knowledge is determined in the routing function below, which checks this flag in the state to decide the next node in the workflow.
        "response": state.get("response", "")
    }


# -------------------------------
# Node 2: Research
# -------------------------------

def do_research(state: AgentState): # This node is responsible for performing research when the agent determines that the current knowledge base does not contain sufficient information to answer the user's query. It uses the LLM to generate a search query for ArXiv, ingests new papers based on that query, and then retrieves updated context from the knowledge base to be used in the final answer generation step.

    print("--- NODE: DO RESEARCH ---")

    query = state["query"]
    history_str = format_history(state["chat_history"])
    contextual_query = build_contextual_query(query, state["chat_history"])

    if contextual_query != query:
        print(f"[QUERY REWRITE] Research query expanded to: {contextual_query}")

    search_prompt = f"""
Generate a concise ArXiv search phrase using 2 to 6 terms.
Return ONLY the search phrase.
Do not add quotes.
Do not add labels.
Do not add explanation.

Example output:
multimodal model comparison

Conversation History:
{history_str}

Question:
{contextual_query}
"""

    raw_arxiv_message = llm.invoke(search_prompt)
    raw_arxiv_query = str(getattr(raw_arxiv_message, "content", "")).strip()
    arxiv_queries = build_arxiv_queries(contextual_query, raw_arxiv_query)
    arxiv_query = arxiv_queries[0] if arxiv_queries else sanitize_arxiv_query(contextual_query)

    print("ArXiv Search Raw:", raw_arxiv_query)
    print("ArXiv Search Sanitized:", arxiv_query)

    arxiv_sources = []
    try:
        from ingest import ingest_arxiv_papers # ingest is the function we defined in ingest.py that searches ArXiv based on the provided query, downloads the papers, extracts text, and ingests it into Supabase. It returns a list of source labels for the ingested papers, which we can use to provide source information to the user in the final response.
        ingested = ingest_arxiv_papers(arxiv_query, max_results=10, max_papers_to_ingest=2)
        if ingested:
            arxiv_sources = ingested
    except Exception as e:
        print("[RESEARCH WARNING]", str(e))

    documents, metadatas = retrieve_documents(contextual_query)

    context_text = "\n\n".join(str(document) for document in documents)

    sources = list(
        {
            metadata.get("source", "Unknown")
            for metadata in metadatas
            if metadata
        }
    )

    # Remove uninformative "Unknown" entries; fall back to arxiv paper titles
    sources = [s for s in sources if s != "Unknown"]
    if not sources:
        sources = arxiv_sources

    return {
        "query": state["query"],
        "chat_history": state["chat_history"],
        "context": context_text,
        "sources": sources,
        "needs_research": False,
        "response": state.get("response", "")
    }


# -------------------------------
# Node 3: Generate Answer
# -------------------------------

def generate_answer(state: AgentState):

    print("--- NODE: GENERATE ANSWER ---")

    context_text = state["context"]
    query = state["query"]
    history_str = format_history(state["chat_history"])
    sources_text = "\n".join(f"- {source}" for source in state["sources"]) if state["sources"] else "- No sources available"

    if not context_text.strip():
        return {
            "query": state["query"],
            "chat_history": state["chat_history"],
            "context": state["context"],
            "sources": state["sources"],
            "needs_research": False,
            "response": "I could not find enough information in the retrieved papers to answer this question.",
        }

    prompt = f"""
You are an AI Research Assistant.

Conversation History:
{history_str}

Use only the retrieved context below as evidence.
Do not use outside knowledge, prior training, or conversation history as factual evidence.
If the answer is not explicitly supported by the context, say you could not find it in the retrieved papers.
Do not speculate.
Keep the answer concise and grounded.

Retrieved Sources:
{sources_text}

Context:
{context_text}

Question:
{query}

Answer using only the retrieved context. If needed, begin with: "I could not find enough information in the retrieved papers."
"""

    response_message = llm.invoke(prompt)
    response = str(getattr(response_message, "content", "")).strip()

    return {
        "query": state["query"],
        "chat_history": state["chat_history"],
        "context": state["context"],
        "sources": state["sources"],
        "needs_research": False,
        "response": response
    }


# -------------------------------
# Routing Logic
# -------------------------------

def route_research(state: AgentState): # It checks the "needs_research" flag in the state to determine whether the agent should proceed to the "do_research" node (if more research is needed) or skip directly to the "generate_answer" node (if the retrieved knowledge is sufficient). This allows the agent to dynamically adjust its workflow based on the information it has and the user's query.

    if state["needs_research"]:
        return "do_research"

    return "generate_answer"


# -------------------------------
# Build Graph
# -------------------------------

workflow = StateGraph(AgentState) # This initializes a new StateGraph from the langgraph library, which allows us to define a workflow of nodes (functions) that operate on a shared state (AgentState). Each node can modify the state and pass it to the next node in the workflow. The graph also supports conditional routing based on the state, which we use to determine whether to perform research or generate an answer directly based on the retrieved knowledge.

workflow.add_node("retrieve_and_check", retrieve_and_check)
workflow.add_node("do_research", do_research)
workflow.add_node("generate_answer", generate_answer)

workflow.set_entry_point("retrieve_and_check")

workflow.add_conditional_edges( # This adds conditional routing logic to the workflow. After the "retrieve_and_check" node is executed, the "route_research" function is called with the current state. This function checks the "needs_research" flag in the state to determine whether the agent should proceed to the "do_research" node (if more research is needed) or skip directly to the "generate_answer" node (if the retrieved knowledge is sufficient). This allows the agent to dynamically adjust its workflow based on the information it has and the user's query.
    "retrieve_and_check",
    route_research
)

workflow.add_edge("do_research", "generate_answer") # After the "do_research" node is executed, we always want to proceed to the "generate_answer" node to produce the final response for the user, using the updated context and sources obtained from the research step.

workflow.add_edge("generate_answer", END) # END is a special marker from langgraph that indicates the end of the workflow. After the "generate_answer" node is executed, the workflow will terminate and return the final state, which includes the generated response and any relevant sources, back to the caller (in this case, our FastAPI endpoint in main.py).

agent_app = workflow.compile() # This compiles the defined workflow into an executable agent application that can be invoked with an initial state. This allows us to call agent_app.invoke(initial_state) to run the entire workflow synchronously, passing the state through each node and applying the defined logic and routing until we reach the end of the workflow, at which point we get the final state with the generated response ready to be returned to the user.










































# Older Verison of agent.py using OLlama (llama3) on local computer
# from typing import TypedDict, List, Dict, Any
# from langgraph.graph import StateGraph, END
# from langchain_community.llms import Ollama
# from langchain_community.vectorstores import Chroma
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from ingest import ingest_arxiv_papers

# # Initialize models and DB
# llm = Ollama(model="llama3")
# embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
# persist_directory = "./chroma_db"
# vector_db = Chroma(persist_directory=persist_directory, embedding_function=embeddings)

# # 1. Define the Agent's "Memory" (State) - Added chat_history
# class AgentState(TypedDict):
#     query: str
#     chat_history: List[Dict[str, Any]]
#     context: str
#     sources: List[str]
#     needs_research: bool
#     response: str

# # Helper Function: Convert history dict to a readable string for the LLM
# def format_history(history: List[Dict[str, Any]]) -> str:
#     if not history:
#         return "No previous conversation."
    
#     formatted_msgs =[]
#     for msg in history:
#         role = "User" if msg["role"] == "user" else "AI Assistant"
#         formatted_msgs.append(f"{role}: {msg['content']}")
#     return "\n".join(formatted_msgs)

# # 2. Node 1: Retrieve and Check Knowledge
# def retrieve_and_check(state: AgentState):
#     print("--- NODE: RETRIEVE & CHECK ---")
#     query = state["query"]
#     history_str = format_history(state["chat_history"])
    
#     # Search existing DB
#     docs = vector_db.similarity_search(query, k=3)
#     context_text = "\n\n".join([doc.page_content for doc in docs])
#     sources = list(set([doc.metadata.get("source", "Unknown") for doc in docs]))
    
#     # Evaluator now knows the conversation history!
#     decision_prompt = f"""
#     You are a strict evaluator. Read the conversation history, the user's latest query, and the retrieved context.
#     Does the retrieved context contain enough relevant information to answer the latest query?
#     Reply with EXACTLY "YES" or "NO".
    
#     Conversation History:
#     {history_str}
    
#     Latest Query: {query}
#     Retrieved Context: {context_text}
#     """
#     decision = llm.invoke(decision_prompt).strip().upper()
#     print(f"Agent Knowledge Check Decision: {decision}")
    
#     needs_research = "NO" in decision or not context_text.strip()
    
#     return {"context": context_text, "sources": sources, "needs_research": needs_research}

# # 3. Node 2: Execute Research Tools (Stage 2 Pipeline)
# def do_research(state: AgentState):
#     print("--- NODE: DO RESEARCH (DOWNLOADING NEW PAPER) ---")
#     query = state["query"]
#     history_str = format_history(state["chat_history"])
    
#     # AI uses history to generate better search keywords for follow-ups
#     search_query_prompt = f"""
#     Based on the conversation history and the latest question, generate a 2 to 3 keyword search phrase for ArXiv.
#     ONLY output the keywords.
    
#     Conversation History:
#     {history_str}
    
#     Latest Question: {query}
#     """
#     arxiv_query = llm.invoke(search_query_prompt).strip()
#     print(f"Generated ArXiv Search Query: {arxiv_query}")
    
#     ingest_arxiv_papers(arxiv_query, max_results=1)
    
#     # Search the DB again now that we have new data
#     docs = vector_db.similarity_search(query, k=3)
#     context_text = "\n\n".join([doc.page_content for doc in docs])
#     sources = list(set([doc.metadata.get("source", "Unknown") for doc in docs]))
    
#     return {"context": context_text, "sources": sources}

# # 4. Node 3: LLM Reasoning (Generate Final Answer)
# def generate_answer(state: AgentState):
#     print("--- NODE: GENERATE ANSWER ---")
#     context_text = state["context"]
#     query = state["query"]
#     history_str = format_history(state["chat_history"])
    
#     # AI uses history to format its final response correctly
#     prompt = f"""You are an AI Research Assistant. Use the retrieved research context and the conversation history to answer the user's latest question. 
    
#     Conversation History:
#     {history_str}

#     Retrieved Context:
#     {context_text}

#     Latest Question:
#     {query}

#     Answer:"""
    
#     response = llm.invoke(prompt)
#     return {"response": response}

# # 5. Routing Logic & Graph Build
# def route_research(state: AgentState):
#     if state["needs_research"]:
#         return "do_research"
#     return "generate_answer"

# workflow = StateGraph(AgentState)
# workflow.add_node("retrieve_and_check", retrieve_and_check)
# workflow.add_node("do_research", do_research)
# workflow.add_node("generate_answer", generate_answer)

# workflow.set_entry_point("retrieve_and_check")
# workflow.add_conditional_edges("retrieve_and_check", route_research)
# workflow.add_edge("do_research", "generate_answer")
# workflow.add_edge("generate_answer", END)

# agent_app = workflow.compile()